language: swift
osx_image: xcode10.2
env:
   - DESTINATION="OS=12.2,name=iPhone XS" SCHEME="CocoaMQTT" SDK=iphonesimulator12.2

before_install:
   - wget https://www.emqx.io/downloads/broker/v3.1.2/emqx-macosx-v3.1.2.zip -O emqx.zip
   - unzip emqx.zip
   - emqx/bin/emqx start

before_script:
   - carthage update --platform iOS

script:
   - xcodebuild clean build -project CocoaMQTT.xcodeproj -scheme "$SCHEME" -sdk "$SDK"
   - xcodebuild -project CocoaMQTT.xcodeproj -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" build test | xcpretty
