language: swift
osx_image: xcode11.1
xcode_project: CocoaMQTT.xcodeproj
xcode_scheme: CocoaMQTT
xcode_destination: platform=iOS Simulator,OS=12.2,name=iPhone Xs
xcode_sdk: iphonesimulator12.2

before_install:
   - wget https://www.emqx.io/downloads/broker/v3.1.2/emqx-macosx-v3.1.2.zip -O emqx.zip
   - unzip emqx.zip
   - emqx/bin/emqx start

before_script:
   - carthage update --platform iOS

